# RunFlare / Liara — proxy everything to Django (WhiteNoise serves /static/)
client_max_body_size 100M;

location / {
  try_files /dev/null @django_app;
}

location ~\.sqlite3$ {
  deny all;
  error_page 403 =404 /;
}

location ~ /\.well-known {
  allow all;
}
