# Generated by Django 5.2.5 on 2025-08-25 06:01

import common.validators
import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('category_type', models.CharField(choices=[('game', 'بازی'), ('ai', 'هوش مصنوعی'), ('software', 'نرم\u200cافزار'), ('service', 'سرویس'), ('entertainment', 'سرگرمی'), ('productivity', 'بهره\u200cوری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع دسته\u200cبندی')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='کلاس آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('seo_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='کلمات کلیدی SEO')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='common.category', verbose_name='دسته\u200cبندی والد')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیحات کوتاه')),
                ('product_type', models.CharField(choices=[('account', 'حساب کاربری'), ('service', 'سرویس'), ('software', 'نرم\u200cافزار'), ('game', 'بازی'), ('subscription', 'اشتراک'), ('other', 'سایر')], default='account', max_length=20, verbose_name='نوع محصول')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), common.validators.validate_price_positive], verbose_name='قیمت اصلی')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='قیمت تخفیف')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت تمام شده')),
                ('currency', models.CharField(choices=[('USD', 'دلار آمریکا'), ('EUR', 'یورو'), ('GBP', 'پوند انگلیس'), ('IRR', 'ریال ایران'), ('BTC', 'بیت\u200cکوین'), ('ETH', 'اتریوم')], default='USD', max_length=3, verbose_name='واحد پول')),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[common.validators.validate_stock_quantity], verbose_name='موجودی')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5, verbose_name='حد کمبود موجودی')),
                ('is_unlimited_stock', models.BooleanField(default=False, verbose_name='موجودی نامحدود')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('inactive', 'غیرفعال'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('delivery_method', models.CharField(choices=[('instant', 'فوری'), ('email', 'ایمیل'), ('manual', 'دستی'), ('api', 'API')], default='instant', max_length=20, verbose_name='روش تحویل')),
                ('delivery_time', models.PositiveIntegerField(default=0, help_text='زمان تحویل به دقیقه', verbose_name='زمان تحویل')),
                ('auto_fulfill', models.BooleanField(default=True, verbose_name='تکمیل خودکار')),
                ('features', models.JSONField(blank=True, default=dict, verbose_name='ویژگی\u200cها')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='مشخصات')),
                ('requirements', models.TextField(blank=True, verbose_name='نیازمندی\u200cها')),
                ('instructions', models.TextField(blank=True, verbose_name='دستورالعمل\u200cها')),
                ('main_image', models.ImageField(upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='تصاویر اضافی')),
                ('video_url', models.URLField(blank=True, verbose_name='لینک ویدیو')),
                ('meta_title', models.CharField(blank=True, max_length=60, verbose_name='عنوان متا')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='توضیحات متا')),
                ('seo_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None, verbose_name='کلمات کلیدی SEO')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خرید')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='میانگین امتیاز')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='پرفروش')),
                ('is_new', models.BooleanField(default=True, verbose_name='جدید')),
                ('is_trending', models.BooleanField(default=False, verbose_name='محبوب')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('sale_start_date', models.DateTimeField(blank=True, null=True, verbose_name='شروع تخفیف')),
                ('sale_end_date', models.DateTimeField(blank=True, null=True, verbose_name='پایان تخفیف')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='common.category', verbose_name='دسته\u200cبندی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='products/images/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='common.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('price_modifier', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='تغییر قیمت')),
                ('stock_quantity', models.PositiveIntegerField(default=0, validators=[common.validators.validate_stock_quantity], verbose_name='موجودی')),
                ('is_unlimited_stock', models.BooleanField(default=False, verbose_name='موجودی نامحدود')),
                ('attributes', models.JSONField(default=dict, verbose_name='ویژگی\u200cها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='common.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5), common.validators.validate_rating_range], verbose_name='امتیاز')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظر')),
                ('comment', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_verified_purchase', models.BooleanField(default=True, verbose_name='خرید تایید شده')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='رای مفید')),
                ('total_votes', models.PositiveIntegerField(default=0, verbose_name='کل رای\u200cها')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='حذف شده توسط')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='common.product', verbose_name='محصول')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slug')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='رنگ تگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی شده توسط')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='common.tag', verbose_name='تگ\u200cها'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type', 'is_active'], name='common_cate_categor_c6539c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='common_cate_slug_ba850e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=django.contrib.postgres.indexes.GinIndex(fields=['seo_keywords'], name='common_cate_seo_key_5f9954_gin'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_active'], name='common_prod_product_feeca3_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active'], name='common_prod_product_df933b_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['sku'], name='common_prod_sku_6a6786_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'is_approved'], name='common_revi_product_77a15e_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='common_revi_rating_9a6893_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase'], name='common_revi_is_veri_cb7bab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product', 'order')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='common_tag_slug_3c24fc_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['is_featured'], name='common_tag_is_feat_82cc2e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_type', 'is_active'], name='common_prod_product_5f9ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='common_prod_categor_8edb25_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status', 'is_active'], name='common_prod_status_be9dbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='common_prod_is_feat_afc13e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_bestseller'], name='common_prod_is_best_c8f18d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='common_prod_rating_0a41e2_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['published_at'], name='common_prod_publish_9158d8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_start_date', 'sale_end_date'], name='common_prod_sale_st_988993_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['seo_keywords'], name='common_prod_seo_key_60a865_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['features'], name='common_prod_feature_111e47_gin'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['specifications'], name='common_prod_specifi_b0b78c_gin'),
        ),
    ]
