# Generated by Django 5.2.5 on 2025-08-25 05:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید به فرمت +989123456789 باشد.', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('user_type', models.CharField(choices=[('customer', 'مشتری'), ('admin', 'مدیر'), ('staff', 'کارمند'), ('vendor', 'فروشنده'), ('moderator', 'ناظر')], default='customer', max_length=20, verbose_name='نوع کاربر')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق'), ('banned', 'مسدود'), ('pending', 'در انتظار تایید')], default='active', max_length=20, verbose_name='وضعیت')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('is_phone_verified', models.BooleanField(default=False, verbose_name='تلفن تایید شده')),
                ('email_verification_token', models.CharField(blank=True, max_length=100, verbose_name='توکن تایید ایمیل')),
                ('phone_verification_code', models.CharField(blank=True, max_length=6, verbose_name='کد تایید تلفن')),
                ('verification_method', models.CharField(choices=[('email', 'ایمیل'), ('phone', 'تلفن'), ('both', 'هر دو'), ('none', 'بدون تایید')], default='email', max_length=20, verbose_name='روش تایید')),
                ('language', models.CharField(default='fa', max_length=10, verbose_name='زبان')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='تعداد ورود')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='آخرین IP ورود')),
                ('email_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید ایمیل')),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید تلفن')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='آخرین فعالیت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='توکن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'توکن بازنشانی رمز عبور',
                'verbose_name_plural': 'توکن\u200cهای بازنشانی رمز عبور',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('website', models.URLField(blank=True, verbose_name='وب\u200cسایت')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='موقعیت جغرافیایی')),
                ('is_profile_public', models.BooleanField(default=True, verbose_name='پروفایل عمومی')),
                ('show_email', models.BooleanField(default=False, verbose_name='نمایش ایمیل')),
                ('show_phone', models.BooleanField(default=False, verbose_name='نمایش تلفن')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای ایمیل')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='اعلان\u200cهای پیامک')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای push')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='کلید جلسه')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'جلسه کاربر',
                'verbose_name_plural': 'جلسات کاربران',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='authenticat_email_390f00_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='authenticat_phone_n_ac3bab_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='authenticat_user_ty_e386f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='authenticat_status_d530a1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified'], name='authenticat_is_emai_cef6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_phone_verified'], name='authenticat_is_phon_dfd514_idx'),
        ),
    ]
