# Generated by Django 4.2.2 on 2025-08-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_user_avatar_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_file',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='فایل تصویر پروفایل'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='آدرس تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تصویر پروفایل (قدیمی)'),
        ),
    ]
