# Generated by Django 4.2.2 on 2025-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
