# Generated by Django 4.2.2 on 2025-11-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_increase_order_number_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='content',
            field=models.TextField(blank=True, help_text='اطلاعات محصول مثل username/password، کلید محصول، لینک دانلود و...', verbose_name='محتوای محصول'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/files/', verbose_name='فایل دانلود'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='download_url',
            field=models.URLField(blank=True, verbose_name='لینک دانلود'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='تحویل شده'),
        ),
    ]
