# Generated by Django 5.2.5 on 2025-11-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cartitem_deliverables'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cart_carti_cart_id_dc3b32_idx',
        ),
    ]
